version: '3.4'

services:
  mysql:
    platform: linux/amd64
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_USER: dev
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_PASSWORD: dev
    volumes:
      - volume-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - networks-database

volumes:
  volume-data:

networks:
  networks-database:
    name: database