version: '3.9'

services:
  postgres-db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: tech55_auth
    ports:
      - "5432:5432"
    networks:
      - networks-database
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistir dados em um volume

volumes:
  pgdata:
    driver: local

networks:
  networks-database:
    name: database