version: '3.4'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:

      SA_PASSWORD: "P@123456"
      ACCEPT_EULA: "Y"
      # MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - networks-database
    volumes:
      - mysql-volume:/var/opt/mssql

volumes:
  mysql-volume:

networks:
  networks-database:
    name: database
    
  # mssqltools:
  #   image: mcr.microsoft.com/mssql-tools
  #   depends_on:
  #     - sqlserver
  #   volumes:
  #     - ./01-BaseGeografica.sql:/tmp/01-BaseGeografica.sql
  #     - ./02-BaseGeografica.sql:/tmp/02-BaseGeografica.sql
  #     - ./init-basegeografica.sh:/tmp/init-basegeografica.sh
  #   command: /bin/bash ./tmp/init-basegeografica.sh


  #docker compose -f compose/database/sqlserver-compose.yml --project-directory databases  up --build -d