version: '3.4'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    restart: always
    ports:
      - '8000:8000'
    networks:
      - networks-aws

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    depends_on:
      - dynamodb-local
    ports:
      - '8001:8001'
    networks:
      - networks-aws
    environment:
      DYNAMO_ENDPOINT: 'http://dynamodb-local:8000'
      AWS_REGION: 'us-east-1'
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local

networks:
  networks-aws:
    name: aws_network