receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - http://localhost:8080
      grpc:

processors:
  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8090

  otlphttp:
    endpoint: http://tempo:4318

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: true
      job: true
      instance: true
      service: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]

    logs:
      receivers: [otlp]
      exporters: [loki]