version: '3.4'

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - networks-rabbit

networks:
  networks-rabbit:
    name: rabbit_network