version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.8.0
    build:
      context: elastic/elasticsearch/
      args:
        - ELASTIC_VERSION=7.8.0
    volumes:
      - ./elastic/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elastic
  
  logstash:
    container_name: logstash
    build:
      context: elastic/logstash/
      args:
        - ELASTIC_VERSION=7.8.0
    volumes:
      - ./elastic/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic
    depends_on:
      - elasticsearch
  
  kibana:
    container_name: kibana
    image: kibana:7.8.0
    build:
      context: elastic/kibana/
      args:
        - ELASTIC_VERSION=7.8.0
    volumes:
      - ./elastic/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch
  apm-server:
    container_name: apm-server
    image: apm-server:7.8.0
    build:
      context: elastic/apm-server/
      args:
        - ELASTIC_VERSION=7.8.0
    volumes:
      - ./elastic/apm-server/config/apm-server.yml:/usr/share/apm-server/config/apm-server.yml:ro
    ports:
      - "8200:8200"
      - "8201:8200"
    networks:
      - elastic
    depends_on:
      - elasticsearch
networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch_data: null